"use client";
import { useState } from "react";
import { useLocale } from "next-intl";
import { RefreshCw, RotateCcw } from "lucide-react";
import { useRemoteResource } from "@/hooks/useRemoteResource";
import Modal from "@/components/ui/Modal";
import { api, requestKey } from "@/lib/client-api";

export default function OperationsPage() {
  const zh = useLocale() === "zh";
  const { data, error, loading, reload } = useRemoteResource("/api/admin/operations");
  const [operation, setOperation] = useState(null);
  const [reason, setReason] = useState("");
  const [amount, setAmount] = useState("");
  const [saving, setSaving] = useState(false);
  const [failure, setFailure] = useState("");
  const choose = (action, id) => { setOperation({ action, id, key: requestKey() }); setReason(""); setAmount(""); setFailure(""); };
  async function submit(event) {
    event.preventDefault(); setSaving(true); setFailure("");
    try { const { key, ...body } = operation; await api("/api/admin/operations", { method: "POST", key, body: { ...body, reason, ...(body.action === "refund" ? { amountMinor: Number(amount) } : {}) } }); setOperation(null); reload(); }
    catch (err) { setFailure(err.code); } finally { setSaving(false); }
  }
  return <div><div className="page-heading"><h1>{zh ? "运行与账务处理" : "Operations"}</h1><button className="button compact" onClick={() => choose("compensate", "")}>{zh ? "退还生成费用" : "Compensate output"}</button><button className="icon-button" title={zh ? "刷新" : "Refresh"} aria-label={zh ? "刷新" : "Refresh"} onClick={reload}><RefreshCw size={18} /></button></div>{(error || failure) && <p role="alert">{failure || (zh ? "加载失败" : "Load failed")}</p>}{loading ? <p>{zh ? "加载中" : "Loading"}</p> : data && <>
    <section className="account-section"><h2>{zh ? "运行状态" : "Service status"}</h2><div className="usage-metrics">{Object.entries(data.metrics).map(([key, value]) => <div key={key}><span>{key}</span><strong>{value ?? "-"}</strong></div>)}</div><p role="status">{data.alerts.join(" / ") || (zh ? "未触发告警" : "No alerts")}</p></section>
    <section className="account-section"><h2>{zh ? "支付事件" : "Payment events"}</h2><div className="table-scroll"><table className="workflow-table"><tbody>{data.events.map(row => <tr key={row.id}><td>{row.id}<small>{row.type}</small></td><td>{row.state}<small>{row.errorCode}</small></td><td>{row.attempts}</td><td><button className="icon-button" title={zh ? "重放" : "Replay"} aria-label={zh ? "重放" : "Replay"} onClick={() => choose("replay_payment", row.id)}><RotateCcw size={16} /></button></td></tr>)}</tbody></table></div></section>
    <section className="account-section"><h2>{zh ? "退款与审核" : "Refunds and review"}</h2><div className="table-scroll"><table className="workflow-table"><tbody>{data.orders.map(row => <tr key={row.id}><td>{row.id}</td><td>{new Intl.NumberFormat(undefined, { style: "currency", currency: row.currency }).format(row.amountMinor / 100)}<small>{row.status}</small></td><td><button className="button compact" onClick={() => choose("refund", row.id)}>{zh ? "退款" : "Refund"}</button>{row.manualReview && <button className="button compact" onClick={() => choose("resolve_review", row.id)}>{zh ? "处理审核" : "Resolve review"}</button>}</td></tr>)}</tbody></table></div><div className="table-scroll"><table className="workflow-table"><tbody>{data.refunds.map(row => <tr key={row.id}><td>{row.orderId}</td><td>{row.amountMinor}</td><td>{row.status}</td><td>{row.errorCode}</td><td>{row.status === "review" && <button className="button compact" onClick={() => choose("resolve_refund_request", row.id)}>{zh ? "核实未执行" : "Confirm not applied"}</button>}</td></tr>)}</tbody></table></div></section>
    <section className="account-section"><h2>{zh ? "订阅变更" : "Subscription changes"}</h2><div className="table-scroll"><table className="workflow-table"><tbody>{data.subscriptionChanges.map(row => <tr key={row.id}><td>{row.subscriptionId}</td><td>{row.input.action}</td><td>{row.state}<small>{row.errorCode}</small></td><td>{row.state === "review" && <button className="button compact" onClick={() => choose("resolve_subscription_change", row.id)}>{zh ? "核实结果" : "Resolve outcome"}</button>}</td></tr>)}</tbody></table></div></section>
    <section className="account-section"><h2>{zh ? "管理审计" : "Audit log"}</h2><div className="table-scroll"><table className="workflow-table"><tbody>{data.audit.map(row => <tr key={row.id}><td>{new Date(row.createdAt).toLocaleString()}</td><td>{row.action}</td><td>{row.detail}</td></tr>)}</tbody></table></div></section>
  </>}{operation && <Modal label={zh ? "确认操作" : "Confirm operation"} onClose={() => { if (!saving) setOperation(null); }}><form onSubmit={submit}><h2>{zh ? "确认操作" : "Confirm operation"}</h2>{operation.action === "compensate" ? <label>{zh ? "生成记录 ID" : "Output ID"}<input required value={operation.id} onChange={e => setOperation(row => ({ ...row, id: e.target.value }))} /></label> : <p>{operation.id}</p>}{operation.action === "resolve_review" && <p>{zh ? "回收尚未使用的退款权益，已消耗部分记为平台承担。仍有预留时不能结案。" : "Reclaim remaining refunded credits and write off consumed credits. Pending reservations prevent resolution."}</p>}{operation.action === "refund" && <label>{zh ? "退款金额（美分）" : "Refund amount (USD cents)"}<input type="number" min="1" step="1" required value={amount} onChange={e => setAmount(e.target.value)} /></label>}{["resolve_refund_request", "resolve_subscription_change"].includes(operation.action) && <><label>{zh ? "支付平台核查记录" : "Provider investigation reference"}<input required minLength={3} maxLength={500} value={operation.reference || ""} onChange={e => setOperation(row => ({ ...row, reference: e.target.value }))} /></label><label>{zh ? "已核实结果" : "Verified outcome"}<select required value={operation.outcome || ""} onChange={e => setOperation(row => ({ ...row, outcome: e.target.value }))}><option value="">{zh ? "选择结果" : "Select outcome"}</option><option value="failed">{zh ? "确认未执行" : "Confirmed not applied"}</option>{operation.action === "resolve_subscription_change" && <option value="done">{zh ? "确认已执行" : "Confirmed applied"}</option>}</select></label></>}<label>{zh ? "原因" : "Reason"}<input required minLength={3} maxLength={500} value={reason} onChange={e => setReason(e.target.value)} /></label><div className="dialog-actions"><button className="button primary" disabled={saving}>{zh ? "确认" : "Confirm"}</button></div></form></Modal>}</div>;
}
