import { test, expect } from "@playwright/test";
import { PrismaClient } from "@prisma/client";
import { PrismaPg } from "@prisma/adapter-pg";
import bcrypt from "bcryptjs";
import fs from "node:fs/promises";
import JSZip from "jszip";
import sharp from "sharp";
import { getTestEnvironment } from "../support/environment.mjs";
import { E2E_PASSWORD } from "../support/e2e-users.mjs";

test("home, gallery, case and editable storyboard lead to real layout exports", async ({ page }, info) => {
  const errors = []; page.on("pageerror", e => errors.push(e.message));
  await page.goto("/zh");
  await expect(page.getByRole("heading", { name: /让想象，\s*有形。/ })).toBeVisible();
  await expect(page.locator(".cr-case")).toHaveCount(8);
  await expect.poll(() => page.locator(".cr-case img").evaluateAll(imgs => imgs.every(img => img.complete && img.naturalWidth > 0))).toBe(true);
  await page.screenshot({ path: info.outputPath("creative-home.png"), fullPage: true });
  await page.getByRole("button", { name: "电商套图", exact: true }).click();
  await expect(page.locator(".cr-case")).toHaveCount(2);
  await page.getByRole("link", { name: "把日常，过成喜欢的样子", exact: true }).click();
  await expect(page.locator(".cm-preview-render")).toHaveCount(6);
  await expect.poll(() => page.locator(".cm-preview-render").evaluateAll(cs => cs.every(c => c.width === 750))).toBe(true);
  await page.screenshot({ path: info.outputPath("creative-case.png"), fullPage: false });
  await page.getByRole("link", { name: "使用这份版式", exact: true }).click();
  await expect(page.getByLabel("产品名称", { exact: true })).toHaveValue("休闲椅");
  await page.getByLabel("品牌名", { exact: true }).fill("物间");
  await page.screenshot({ path: info.outputPath("commerce-brief.png"), fullPage: true });
  await page.getByRole("button", { name: "生成可编辑分镜", exact: true }).click();
  await expect(page.locator(".cm-section-list>button")).toHaveCount(6);
  await page.getByLabel("标题", { exact: true }).fill("把日常，过成喜欢的样子");
  await page.getByLabel("正文", { exact: true }).fill("一处安静角落，一段属于自己的时光。");
  await page.getByLabel("版式", { exact: true }).selectOption("inset");
  await expect(page.getByRole("button", { name: "下载生成套图", exact: true })).toBeDisabled();
  const downloaded = page.waitForEvent("download");
  await page.getByRole("button", { name: "导出原图排版", exact: true }).click();
  const file = await downloaded, zip = await JSZip.loadAsync(await fs.readFile(await file.path()));
  const project = JSON.parse(await zip.file("project.json").async("string"));
  expect(project.source).toBe("original-photo-layout"); expect(project.brief.brand).toBe("物间");
  expect(project.sections[0].title).toBe("把日常，过成喜欢的样子");
  const meta = await sharp(await zip.file("detail-page.png").async("nodebuffer")).metadata();
  expect(meta.width).toBe(750); expect(meta.height).toBe(5178);
  await page.screenshot({ path: info.outputPath("commerce-storyboard.png"), fullPage: false });
  await page.goto("/zh/commerce");
  await expect(page.getByLabel("标题", { exact: true })).toHaveValue("把日常，过成喜欢的样子");
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true);
  expect(errors).toEqual([]);
  await page.goto("/zh");
  await page.getByRole("tab", { name: /电商套图 Agent/ }).click();
  await page.getByLabel("产品名称", { exact: true }).fill("黄铜台灯");
  await page.getByLabel("品牌名", { exact: true }).fill("暮光");
  await page.getByLabel("目标平台", { exact: true }).selectOption("shopify");
  await page.getByLabel("地区", { exact: true }).selectOption("US");
  await page.getByLabel("文案语言", { exact: true }).selectOption("en");
  await page.screenshot({ path: info.outputPath("home-commerce.png"), fullPage: false });
  await page.getByRole("button", { name: "开始电商创作", exact: true }).click();
  await expect(page.getByLabel("产品名称", { exact: true })).toHaveValue("黄铜台灯");
  await expect(page.getByLabel("目标平台", { exact: true })).toHaveValue("shopify");
  await expect(page.getByLabel("地区", { exact: true })).toHaveValue("US");
  await expect(page.getByLabel("文案语言", { exact: true })).toHaveValue("en");
  await page.getByLabel("品牌名", { exact: true }).fill("暮光 2");
  await page.reload();
  await expect(page.getByLabel("品牌名", { exact: true })).toHaveValue("暮光 2");
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true);
});

test("commerce keeps two image roles, six independent jobs, replay and cloud recovery", async ({ page }, info) => {
  const db = new PrismaClient({ adapter: new PrismaPg({ connectionString: getTestEnvironment().databaseUrl }) });
  const email = `commerce-${info.project.name}-${Date.now()}@modelshot.test`;
  try {
    const user = await db.user.create({ data: { email, passwordHash: await bcrypt.hash(E2E_PASSWORD, 10), credits: 300, emailVerified: new Date() } });
    await page.goto("/en/login?callbackUrl=/en/commerce?case=quiet-living");
    await page.getByRole("button", { name: "Email", exact: true }).click();
    await page.getByLabel("Email", { exact: true }).fill(email); await page.getByLabel("Password", { exact: true }).fill(E2E_PASSWORD); await page.getByRole("button", { name: "Sign in", exact: true }).click();
    await expect(page.getByLabel("Product name", { exact: true })).toHaveValue("Lounge chair");
    await page.goto("/en");
    await page.getByRole("tab", { name: /Commerce Agent/ }).click();
    await page.getByLabel("Product name", { exact: true }).fill("Lounge chair");
    await page.getByLabel("Upload product image", { exact: true }).setInputFiles("public/inspiration/chair.webp");
    await expect(page.locator(".cr-home-image img")).toHaveCount(1);
    await page.getByLabel("Upload style reference", { exact: true }).setInputFiles("public/inspiration/skincare.webp");
    await expect(page.locator(".cr-home-image img")).toHaveCount(2);
    await page.getByRole("button", { name: "Start product story", exact: true }).click();
    await expect(page.locator(".cm-upload.has-image")).toHaveCount(2);
    const saved = page.waitForResponse(r => r.url().endsWith("/api/studio/documents") && r.request().method() === "POST");
    await page.getByRole("button", { name: "Create storyboard", exact: true }).click();
    const doc = await (await saved).json(); expect(doc.content.commerce.productAssetId).not.toBe(doc.content.commerce.referenceAssetId);
    const submitted = page.waitForResponse(r => r.url().endsWith("/api/commerce/run"));
    await page.getByRole("button", { name: /Generate remaining sections/ }).click();
    const response = await submitted, submittedBody = response.request().postDataJSON(), result = await response.json();
    expect(result.failure).toBeNull(); expect(result.jobs).toHaveLength(6);
    const replay = await page.request.post("/api/commerce/run", { data: submittedBody }); expect((await replay.json()).jobs.map(j => j.id)).toEqual(result.jobs.map(j => j.id));
    await expect.poll(async () => (await db.tryOn.findMany({ where: { id: { in: result.jobs.map(j => j.id) } } })).filter(j => j.status === "succeeded").length, { timeout: 60000 }).toBe(6);
    const rows = await db.tryOn.findMany({ where: { id: { in: result.jobs.map(j => j.id) } } });
    expect(rows.every(j => j.snapshot.assetId === doc.content.commerce.productAssetId)).toBe(true);
    expect(rows.every(j => j.snapshot.referenceAssetIds[0] === doc.content.commerce.referenceAssetId)).toBe(true);
    expect((await db.user.findUnique({ where: { id: user.id } })).credits).toBe(192);
    await page.goto(`/en/commerce?document=${doc.id}`);
    await expect(page.getByRole("button", { name: "Download generated set", exact: true })).toBeEnabled();
    const download = page.waitForEvent("download"); await page.getByRole("button", { name: "Download generated set", exact: true }).click();
    expect((await download).suggestedFilename()).toBe("modelshot-product-story.zip");
    await page.getByRole("button", { name: "Continue in canvas", exact: true }).click();
    await expect(page).toHaveURL(/studio-v2\?document=/, { timeout: 40000 });
    await expect(page.locator(".ms-canvas-label")).toContainText("24 layers");
    await page.goto("/en/projects");
    await expect(page.locator(".cr-project-card")).toHaveCount(2);
  } finally { await db.$disconnect(); }
});
