import { test, expect } from "@playwright/test";
import { PrismaClient } from "@prisma/client";
import { PrismaPg } from "@prisma/adapter-pg";
import bcrypt from "bcryptjs";
import { encryptSecret } from "../../src/lib/crypto.js";
import { getTestEnvironment } from "../support/environment.mjs";
import { E2E_PASSWORD } from "../support/e2e-users.mjs";

test("inspiration and homepage carry a brief into the agent without fabricating template results", async ({ page }) => {
  await page.goto("/zh/explore/quiet-living");
  await expect(page.locator(".cm-preview-render")).toHaveCount(6);
  await page.getByRole("link", { name: "使用这份版式", exact: true }).click();
  await expect(page.getByLabel("产品名称", { exact: true })).toHaveValue("休闲椅");
  await expect(page.getByRole("button", { name: "开始策划", exact: true })).toBeDisabled();
  await expect(page.locator(".ca-card")).toHaveCount(0);
  await page.goto("/zh");
  await page.getByRole("tab", { name: /电商套图 Agent/ }).click();
  await page.getByLabel("产品名称", { exact: true }).fill("黄铜台灯");
  await page.getByLabel("品牌名", { exact: true }).fill("暮光");
  await page.getByLabel("目标平台", { exact: true }).selectOption("shopify");
  await page.getByRole("button", { name: "开始电商创作", exact: true }).click();
  await expect(page.getByLabel("产品名称", { exact: true })).toHaveValue("黄铜台灯");
  await expect(page.getByLabel("平台", { exact: true })).toHaveValue("shopify");
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true);
});

test("commerce uses cloud planning, billed durable jobs, targeted revisions and one persistent canvas", async ({ page }, info) => {
  const db = new PrismaClient({ adapter: new PrismaPg({ connectionString: getTestEnvironment().databaseUrl }) });
  const email = `commerce-${info.project.name}-${Date.now()}@modelshot.test`;
  const oldKey = process.env.ENCRYPTION_KEY;
  const prior = await db.modelProvider.findMany({ where: { isPlanner: true } });
  const plannerName = `commerce-language-${Date.now()}`;
  try {
    process.env.ENCRYPTION_KEY = "ab".repeat(32);
    await db.modelProvider.updateMany({ where: { isPlanner: true }, data: { isPlanner: false } });
    await db.modelProvider.create({ data: { name: plannerName, displayName: "Commerce language fixture", kind: "openai", isActive: true, isPlanner: true, creditCost: 2, costPerImage: 0, config: JSON.stringify({ scope: "language", studioCapability: "language", model: "fixture-language", baseURL: `http://127.0.0.1:${process.env.TEST_PROVIDER_PORT || 3199}/cloud`, apiKeyEnc: encryptSecret("fixture-key") }) } });
    const user = await db.user.create({ data: { email, passwordHash: await bcrypt.hash(E2E_PASSWORD, 10), credits: 300, emailVerified: new Date() } });
    await page.goto("/en/login?callbackUrl=/en/commerce");
    await page.getByRole("button", { name: "Email", exact: true }).click();
    await page.getByLabel("Email", { exact: true }).fill(email);
    await page.getByLabel("Password", { exact: true }).fill(E2E_PASSWORD);
    await page.getByRole("button", { name: "Sign in", exact: true }).click();
    await page.getByLabel("Product", { exact: true }).fill("Lounge chair");
    await page.getByLabel("Product facts & requirements", { exact: true }).fill("Create three lifestyle images for this blue chair");
    await page.getByLabel("Upload product image", { exact: true }).setInputFiles("public/inspiration/chair.webp");
    await expect(page.locator(".ca-uploads img")).toHaveCount(1);
    await page.getByLabel("Upload style reference", { exact: true }).setInputFiles("public/inspiration/skincare.webp");
    await expect(page.locator(".ca-uploads img")).toHaveCount(2);
    await page.getByLabel("Image count", { exact: true }).selectOption("3");
    const planned = page.waitForResponse(r => r.url().endsWith("/api/commerce/plan"));
    await page.getByRole("button", { name: "Plan my collection", exact: true }).click();
    const planningResponse = await planned, { document: doc } = await planningResponse.json();
    expect(doc.content.commerce.sections).toHaveLength(3);
    const replay = await page.request.post("/api/commerce/plan", { data: planningResponse.request().postDataJSON(), headers: { "idempotency-key": planningResponse.request().headers()["idempotency-key"] } });
    expect((await replay.json()).document.id).toBe(doc.id);
    expect((await db.user.findUnique({ where: { id: user.id } })).credits).toBe(298);
    const submitted = page.waitForResponse(r => r.url().endsWith("/api/commerce/run"));
    await page.getByRole("button", { name: /Generate 3 pending/ }).click();
    const response = await submitted, result = await response.json();
    expect(result.failure).toBeNull(); expect(result.jobs).toHaveLength(3);
    await expect.poll(async () => (await db.tryOn.findMany({ where: { id: { in: result.jobs.map(j => j.id) } } })).filter(j => j.status === "succeeded").length, { timeout: 60000 }).toBe(3);
    await expect(page.locator(".ca-card-image img")).toHaveCount(3);
    const rows = await db.tryOn.findMany({ where: { id: { in: result.jobs.map(j => j.id) } } });
    expect(rows.every(j => j.snapshot.assetId === doc.content.commerce.productAssetId)).toBe(true);
    expect(rows.every(j => j.snapshot.referenceAssetIds[0] === doc.content.commerce.referenceAssetId)).toBe(true);
    await page.locator(".ca-card").nth(1).getByRole("button", { name: "Revise", exact: true }).click();
    await page.getByLabel("Continue creating").fill("Use an outdoor scene for this image only");
    await page.getByRole("button", { name: "Send request" }).click();
    await expect(page.locator(".ca-card").nth(1)).toContainText("Outdoor living");
    await expect(page.locator(".ca-card-image img")).toHaveCount(2);
    const updated = await db.studioDocument.findUnique({ where: { id: doc.id } });
    expect(updated.content.commerce.sections[1].attempt).toBe(1);
    expect(updated.content.commerce.sections[1].revisionAssetId).toBeTruthy();
    await page.getByRole("button", { name: "Open canvas", exact: true }).click();
    await expect(page).toHaveURL(new RegExp(`studio-v2\\?document=${doc.id}`));
    const saved = await db.studioDocument.findUnique({ where: { id: doc.id } });
    expect(saved.content.layers.filter(l => l.type === "image")).toHaveLength(5);
    expect(await db.studioDocument.count({ where: { userId: user.id } })).toBe(1);
  } finally {
    await db.modelProvider.deleteMany({ where: { name: plannerName } });
    for (const row of prior) await db.modelProvider.update({ where: { id: row.id }, data: { isPlanner: true } });
    if (oldKey == null) delete process.env.ENCRYPTION_KEY; else process.env.ENCRYPTION_KEY = oldKey;
    await db.$disconnect();
  }
});
