import { test, expect } from "@playwright/test";
import { PrismaClient } from "@prisma/client";
import { PrismaPg } from "@prisma/adapter-pg";
import bcrypt from "bcryptjs";
import sharp from "sharp";
import { getTestEnvironment } from "../support/environment.mjs";
import { E2E_PASSWORD } from "../support/e2e-users.mjs";

test("one EntitySegment channel can be saved for splitting and produces aligned, editable layers", async ({ page }, info) => {
  const db = new PrismaClient({ adapter: new PrismaPg({ connectionString: getTestEnvironment().databaseUrl }) });
  const email = `entity-split-${info.project.name}-${Date.now()}@modelshot.test`;
  const previous = await db.studioToolConfig.findUnique({ where: { toolId: "split" } });
  let providerId;
  const errors = []; page.on("pageerror", error => errors.push(error.message));
  try {
    await db.user.create({ data: { email, passwordHash: await bcrypt.hash(E2E_PASSWORD, 10), role: "root", credits: 100, emailVerified: new Date() } });
    await page.goto("/en/login?callbackUrl=/en/admin/providers");
    await page.getByRole("button", { name: "Email", exact: true }).click();
    await page.getByLabel("Email", { exact: true }).fill(email);
    await page.getByLabel("Password", { exact: true }).fill(E2E_PASSWORD);
    await page.getByRole("button", { name: "Sign in", exact: true }).click();
    await expect(page.getByRole("heading", { name: "模型配置", exact: true })).toBeVisible();
    await page.getByRole("tab", { name: "工具专用模型", exact: true }).click();
    await page.getByRole("button", { name: "新增模型", exact: true }).click();
    await page.getByLabel("配置预设").selectOption({ label: "火山智能视觉 · EntitySegment 物体分割" });
    await page.getByLabel("Access Key ID (AK)", { exact: true }).fill("fixture-entity-ak");
    await page.getByLabel("Secret Access Key (SK)", { exact: true }).fill("fixture-entity-sk");
    const created = page.waitForResponse(r => r.url().endsWith("/api/admin/providers") && r.request().method() === "PUT");
    await page.getByRole("button", { name: "保存新模型", exact: true }).click();
    const response = await created;
    expect(response.status()).toBe(201);
    providerId = (await response.json()).id;
    const provider = await db.modelProvider.findUnique({ where: { id: providerId } });
    expect(provider.config).not.toMatch(/fixture-entity-ak|fixture-entity-sk/);
    // Test requests must only reach the isolated local supplier.
    await db.modelProvider.update({ where: { id: providerId }, data: { config: JSON.stringify({ ...JSON.parse(provider.config), baseURL: "http://127.0.0.1:3199/cloud" }) } });
    const catalog = await (await page.request.get("/api/admin/studio-tools")).json();
    expect(catalog.channels.segment.some(ch => ch.name === provider.name)).toBe(true);
    expect(catalog.channels.split.some(ch => ch.name === provider.name)).toBe(true);
    expect(catalog.channels.image.some(ch => ch.name === provider.name)).toBe(false);
    await page.goto("/en/admin/studio-tools");
    const card = page.getByRole("heading", { name: "图层拆分", exact: true }).locator("xpath=ancestor::div[contains(@class, 'rounded-[14px]')][1]");
    const model = card.locator("label").filter({ hasText: "专用模型" }).last().locator("select");
    await model.selectOption(provider.name);
    const saved = page.waitForResponse(r => r.url().endsWith("/api/admin/studio-tools") && r.request().method() === "PATCH");
    await card.getByRole("button", { name: "保存", exact: true }).click();
    expect((await saved).status()).toBe(200);
    await page.reload();
    await expect(model).toHaveValue(provider.name);
    await card.scrollIntoViewIfNeeded();
    await page.screenshot({ path: info.outputPath("entity-split-admin.png"), fullPage: true });
    const caps = await (await page.request.get("/api/studio/capabilities")).json();
    expect(caps.tools.find(t => t.id === "split")).toMatchObject({ available: true, layerCountMode: "auto" });
    expect(JSON.stringify(caps)).not.toMatch(/fixture-entity|accessKey|secretAccess/);
    await page.goto("/en/studio-v2");
    const source = await sharp({ create: { width: 320, height: 480, channels: 4, background: "#879d8f" } })
      .composite([{ input: await sharp({ create: { width: 80, height: 120, channels: 4, background: "red" } }).png().toBuffer(), left: 80, top: 120 }]).png().toBuffer();
    await page.getByLabel("Upload image files").setInputFiles({ name: "entity-source.png", mimeType: "image/png", buffer: source });
    await expect(page.locator(".ms-image-menu")).toBeVisible();
    await page.getByRole("button", { name: /Split layers/ }).click();
    await expect(page.getByText(/Automatically separate detected regions/)).toBeVisible();
    await expect(page.getByLabel("Layers", { exact: true })).toHaveCount(0);
    const submitted = page.waitForResponse(r => r.url().endsWith("/api/studio/jobs") && r.request().method() === "POST");
    await page.getByRole("button", { name: "Apply 20 credits", exact: true }).click({ force: true });
    const jobResponse = await submitted;
    expect(jobResponse.status()).toBe(202);
    const job = await jobResponse.json();
    await expect.poll(async () => (await (await page.request.get(`/api/studio/jobs/${job.id}`)).json()).status, { timeout: 45000 }).toBe("succeeded");
    const finished = await db.tryOn.findUnique({ where: { id: job.id } });
    expect(finished.snapshot).toMatchObject({ provider: provider.name, providerKind: "volc-visual", imageModel: "entity_seg" });
    expect(finished.resultData).toMatchObject({ placement: "stack" });
    expect(finished.resultData.assets).toHaveLength(2);
    const layers = [];
    for (const asset of finished.resultData.assets) layers.push(await (await page.request.get(`/api/assets/${asset.id}`)).body());
    const merged = await sharp({ create: { width: 320, height: 480, channels: 4, background: { r: 0, g: 0, b: 0, alpha: 0 } } }).composite(layers.map(input => ({ input }))).raw().toBuffer();
    expect(merged.equals(await sharp(source).raw().toBuffer())).toBe(true);
    await expect(page.locator(".ms-canvas-label")).toContainText("3 layers");
    await page.getByRole("button", { name: "Undo", exact: true }).click();
    await expect(page.locator(".ms-canvas-label")).toContainText("1 layers");
    await page.getByRole("button", { name: "Redo", exact: true }).click();
    await expect(page.locator(".ms-canvas-label")).toContainText("3 layers");
    expect((await (await page.request.get("/api/usage")).json()).credits).toBe(80);
    expect(errors).toEqual([]);
  } finally {
    if (previous) await db.studioToolConfig.upsert({ where: { toolId: "split" }, create: previous, update: { routing: previous.routing, creditCost: previous.creditCost, isEnabled: previous.isEnabled } });
    else await db.studioToolConfig.deleteMany({ where: { toolId: "split" } });
    if (providerId) await db.modelProvider.delete({ where: { id: providerId } });
    await db.$disconnect();
  }
});
