import { test, expect } from "@playwright/test";
import { PrismaClient } from "@prisma/client";
import { PrismaPg } from "@prisma/adapter-pg";
import bcrypt from "bcryptjs";
import { getTestEnvironment } from "../support/environment.mjs";
import { E2E_PASSWORD } from "../support/e2e-users.mjs";
import { readStudioDraft } from "../support/studio-draft.mjs";

test("project title, autosave, task popover, history and rename survive navigation", async ({ page }, info) => {
  const db = new PrismaClient({ adapter: new PrismaPg({ connectionString: getTestEnvironment().databaseUrl }) });
  const email = `projects-${info.project.name}-${Date.now()}@modelshot.test`, errors = [];
  page.on("pageerror", error => errors.push(error.message));
  try {
    const user = await db.user.create({ data: { email, passwordHash: await bcrypt.hash(E2E_PASSWORD, 10), credits: 100, emailVerified: new Date() } });
    await page.goto("/en/login?callbackUrl=/en/studio-v2");
    await page.getByRole("button", { name: "Email", exact: true }).click();
    await page.getByLabel("Email", { exact: true }).fill(email);
    await page.getByLabel("Password", { exact: true }).fill(E2E_PASSWORD);
    await page.getByRole("button", { name: "Sign in", exact: true }).click();
    await expect(page.getByLabel("Creative prompt")).toBeVisible();
    await page.getByLabel("Creative prompt").fill("A cat on a windowsill FIXTURE_DELAY");
    await expect(page.getByRole("button", { name: "Generate · 18 credits", exact: true })).toBeEnabled();
    await page.getByRole("button", { name: "Generate · 18 credits", exact: true }).click();
    if (info.project.name === "mobile") await page.getByRole("button", { name: "Canvas", exact: true }).click();
    await page.getByRole("button", { name: "Task list", exact: true }).click();
    await expect(page.locator(".ms-task-card")).toContainText("Generate image");
    await page.screenshot({ path: info.outputPath("task-running.png"), fullPage: true, animations: "disabled" });
    await expect(page).toHaveURL(/document=/);
    const id = new URL(page.url()).searchParams.get("document");
    await expect(page.locator(".ms-task-complete")).toContainText("Tasks complete", { timeout: 45000 });
    await page.screenshot({ path: info.outputPath("task-complete.png"), fullPage: true, animations: "disabled" });
    await expect.poll(async () => (await db.studioDocument.findUnique({ where: { id } }))?.content.layers.length).toBe(1);
    expect(await db.studioDocument.count({ where: { userId: user.id } })).toBe(1);
    const before = await readStudioDraft(page);
    expect(before.name).toBe("A cat on a windowsill FIXTURE_DELAY");
    await page.reload();
    await expect.poll(async () => (await readStudioDraft(page))?.layers.length).toBe(1);
    if (info.project.name === "mobile") await page.getByRole("button", { name: "Canvas", exact: true }).click();
    await page.getByRole("button", { name: "Pan", exact: true }).click();
    const stage = await page.locator(".ms-stage").boundingBox();
    await page.mouse.move(stage.x + stage.width / 2, stage.y + 180); await page.mouse.down(); await page.mouse.move(stage.x + stage.width / 2 + 45, stage.y + 210, { steps: 5 }); await page.mouse.up();
    const camera = JSON.parse(await page.locator(".ms-stage").getAttribute("data-camera"));
    await expect.poll(async () => (await db.studioDocumentView.findUnique({ where: { documentId: id } }))?.camera).toEqual(camera);
    await page.reload();
    if (info.project.name === "mobile") await page.getByRole("button", { name: "Canvas", exact: true }).click();
    await expect.poll(async () => JSON.parse(await page.locator(".ms-stage").getAttribute("data-camera"))).toEqual(camera);
    // A second conversation turn belongs to this canvas and keeps its first title.
    if (info.project.name === "mobile") await page.getByRole("button", { name: "Chat", exact: true }).click();
    await page.getByLabel("Creative prompt").fill("Now make the window blue");
    await page.getByRole("button", { name: "Generate · 18 credits", exact: true }).click();
    await expect.poll(async () => (await db.studioDocument.findUnique({ where: { id } }))?.content.layers.length).toBe(2);
    expect(await db.studioDocument.count({ where: { userId: user.id } })).toBe(1);
    expect((await db.studioDocument.findUnique({ where: { id } })).name).toBe("A cat on a windowsill FIXTURE_DELAY");
    await page.goto("/en/projects");
    await page.getByRole("navigation", { name: "Creative navigation" }).getByRole("link", { name: "Canvas", exact: true }).click();
    await expect(page).toHaveURL(new RegExp(`document=${id}`));
    await expect.poll(async () => (await readStudioDraft(page))?.layers.length).toBe(2);
    await page.goto("/en/projects");
    await expect(page.getByRole("heading", { name: "My projects", exact: true })).toBeVisible();
    await expect(page.locator(".mp-card")).toHaveCount(1);
    await expect(page.locator(".mp-cover img")).toHaveAttribute("src", /preview=640/);
    await expect.poll(() => page.locator(".mp-cover img").evaluateAll(images => images.every(image => image.complete && image.naturalWidth > 0))).toBe(true);
    await page.getByRole("button", { name: /Project menu:/ }).click();
    await page.getByRole("button", { name: "Rename", exact: true }).click();
    await page.getByLabel("Project name", { exact: true }).fill("Window cat project");
    await page.getByRole("button", { name: "Save", exact: true }).click();
    await expect(page.getByRole("heading", { name: "Window cat project", exact: true })).toBeVisible();
    await page.screenshot({ path: info.outputPath("project-library.png"), fullPage: true, animations: "disabled" });
    await page.getByRole("link", { name: "Window cat project", exact: true }).click();
    await expect(page.locator(".ms-project-trigger")).toContainText("Window cat project");
    await expect.poll(async () => (await readStudioDraft(page))?.layers[0]?.assetId).toBe(before.layers[0].assetId);
    await page.goto("/en/projects");
    await page.getByRole("button", { name: /Project menu:/ }).click();
    await page.getByRole("button", { name: "Delete", exact: true }).click();
    await page.getByRole("dialog", { name: "Delete project" }).getByRole("button", { name: "Delete", exact: true }).click();
    await expect(page.locator(".mp-card")).toHaveCount(0);
    await page.getByRole("button", { name: "Deleted", exact: true }).click();
    await page.getByRole("button", { name: "Restore", exact: true }).click();
    await expect(page.locator(".mp-card")).toHaveCount(0);
    await page.getByRole("button", { name: "All", exact: true }).click();
    await expect(page.getByRole("link", { name: "Window cat project", exact: true })).toBeVisible();
    await page.getByRole("button", { name: email, exact: true }).click();
    await page.getByRole("menuitem", { name: "Usage history", exact: true }).click();
    const records = page.getByRole("dialog", { name: "Account records", exact: true });
    await expect(records.getByText("Currently available credits: 64", { exact: false })).toBeVisible();
    await expect(records.locator("tbody tr")).toHaveCount(2);
    await records.getByRole("button", { name: "Purchases", exact: true }).click();
    await expect(records.getByText("No records yet", { exact: true })).toBeVisible();
    await records.getByRole("button", { name: "Help", exact: true }).click();
    await expect(records.getByRole("heading", { name: "Move objects and edit areas", exact: true })).toBeVisible();
    await page.screenshot({ path: info.outputPath("account-help.png"), fullPage: true, animations: "disabled" });
    await page.keyboard.press("Escape");
    await expect(records).toHaveCount(0);
    await expect(page.getByRole("button", { name: email, exact: true })).toBeFocused();
    await page.goto("/en/projects");
    await page.getByRole("link", { name: "New project", exact: true }).click();
    await expect(page).toHaveURL(/draft=/);
    expect(new URL(page.url()).searchParams.get("document")).toBeNull();
    await expect.poll(async () => (await readStudioDraft(page))?.layers.length).toBe(0);
    expect(await db.studioDocument.count({ where: { userId: user.id } })).toBe(1);
    expect(errors).toEqual([]);
  } finally { await db.$disconnect(); }
});
