export const CASES = [
  { id: "quiet-living", category: "commerce", title: "把日常，过成喜欢的样子", en: "The art of slow living", product: "休闲椅", productEn: "Lounge chair", image: "chair", theme: "linen", style: "natural", label: "家居 · 电商详情页", labelEn: "Living · Product story", headline: "SLOW\nLIVING", brief: "以暖白和自然光呈现休闲椅，突出椅背、软垫与整体轮廓。保留原产品外观，不虚构材质或尺寸。", briefEn: "A lounge chair story in warm whites and natural light. Preserve the chair, tufting and silhouette. Do not invent materials or dimensions.", span: "tall" },
  { id: "botanical-light", category: "beauty", title: "一束光，一点自然", en: "A little closer to nature", product: "精华油", productEn: "Facial oil", image: "skincare", theme: "sand", style: "natural", label: "美妆 · 光影摄影", labelEn: "Beauty · Light study", headline: "NATURE\nIN LIGHT", brief: "暖调精华油产品摄影，植物投影、柔和自然光、克制留白。不要添加未经证实的护肤功效。", briefEn: "Warm botanical product photography, leaf shadows and soft natural light. No unsupported skincare claims.", span: "medium" },
  { id: "red-motion", category: "poster", title: "让每一步，自带主场", en: "Make your own momentum", product: "运动鞋", productEn: "Sneaker", image: "sneaker", theme: "red", style: "editorial", label: "运动 · 品牌海报", labelEn: "Sport · Campaign", headline: "MAKE\nYOUR MOVE.", brief: "红色运动鞋的品牌视觉，红色同色系背景、强烈明暗对比、运动感构图。准确保留鞋的外观与标识。", briefEn: "Tonal red sneaker campaign with bold lighting and kinetic composition. Preserve the exact product and markings.", span: "medium" },
  { id: "scent-study", category: "beauty", title: "关于气味的想象", en: "An impression that stays", product: "香水", productEn: "Fragrance", image: "perfume", theme: "ice", style: "editorial", label: "香氛 · 产品摄影", labelEn: "Fragrance · Still life", headline: "a study\nin scent.", brief: "以通透玻璃、浅蓝背景和柔和反射呈现香水。不要改动瓶身比例与现有标签。", briefEn: "Transparent glass against pale blue, gentle reflections. Preserve the exact bottle and existing label.", span: "tall" },
  { id: "sound-space", category: "commerce", title: "给声音，留一点空间", en: "Space for your sound", product: "头戴式耳机", productEn: "Headphones", image: "headphones", theme: "mono", style: "studio", label: "数码 · 主图套组", labelEn: "Tech · Product set", headline: "LESS NOISE.\nMORE YOU.", brief: "头戴式耳机的极简详情页，冷灰背景、清晰的轮廓光、可见结构特写；不添加降噪性能等未确认数据。", briefEn: "Minimal headphone story, cool gray background and precise lighting. Show visible details without unverified performance claims.", span: "medium" },
  { id: "orange-season", category: "poster", title: "把阳光，装进这一季", en: "A season full of sunshine", product: "鲜橙", productEn: "Oranges", image: "citrus", theme: "citrus", style: "editorial", label: "食品 · 社媒海报", labelEn: "Food · Social campaign", headline: "HELLO,\nSUNSHINE.", brief: "鲜橙主题的季节海报，饱满橙色、果皮真实纹理与近景构图。不写产地、含糖量或营养承诺。", briefEn: "Seasonal orange campaign, saturated color and real peel texture. No invented origin or nutrition claims.", span: "tall" },
  { id: "living-journal", category: "space", title: "理想的家，有自己的节奏", en: "A room of your own", product: "家居空间", productEn: "Living space", image: "interior", theme: "linen", style: "natural", label: "空间 · 生活方式", labelEn: "Space · Lifestyle", headline: "the living\njournal.", brief: "暖调家居空间，漫射日光、绿植与原木，呈现生活气息和自然材质。", briefEn: "Warm living space, diffuse daylight, plants and timber, with an editorial sense of everyday life.", span: "medium" },
  { id: "after-dark", category: "poster", title: "光影之间，自有故事", en: "Find your own perspective", product: "相机", productEn: "Camera", image: "camera", theme: "dark", style: "studio", label: "数码 · 暗调静物", labelEn: "Tech · Dark still life", headline: "CHASE\nTHE LIGHT.", brief: "暗调相机产品大片，定向光勾勒轮廓、深黑背景、细节清晰，保留机身与镜头的真实结构。", briefEn: "Dark camera still life with directional lighting, black background and accurate product detail.", span: "tall" },
];
export const getCase = id => CASES.find(item => item.id === id);
export const caseImage = item => `/inspiration/${item.image}.webp`;
export const CATEGORIES = [["all", "全部灵感", "All inspiration"], ["commerce", "电商套图", "Commerce"], ["beauty", "美妆香氛", "Beauty"], ["poster", "创意海报", "Posters"], ["space", "空间场景", "Spaces"]];
