"use client";
import Image from "next/image";
import { useState } from "react";
import { useLocale } from "next-intl";
import { Link } from "@/i18n/navigation";
import { ArrowLeft, ArrowUpRight, Copy, Check, Sparkles, Layers3 } from "lucide-react";
import CreativeShell from "./CreativeShell";
import { caseImage } from "@/lib/commerce/catalog";
import { createStoryboard } from "@/lib/commerce/planner";
import StoryPreview from "@/components/commerce/StoryPreview";
import "@/components/commerce/commerce.css";
export default function CaseDetail({ item }) {
  const zh = useLocale() === "zh", [copied, setCopied] = useState(false), [notice, setNotice] = useState("");
  const brief = { product: zh ? item.product : item.productEn, description: zh ? item.brief : item.briefEn, brand: "", theme: item.theme, style: item.style, language: zh ? "zh" : "en", platform: "taobao", region: "CN" };
  const sections = createStoryboard(brief);
  return <CreativeShell><div className="cr-case-detail"><Link href="/explore" className="cr-back"><ArrowLeft size={16} />{zh ? "返回灵感发现" : "Back to inspiration"}</Link><div className="cr-detail-grid"><div className="cr-detail-art"><div className="cr-preview-top"><span><Layers3 size={14} />{zh ? "完整详情页 · 版式示例" : "Complete page · Layout study"}</span><span>6 {zh ? "屏" : "sections"}</span></div><StoryPreview sections={sections} brief={brief} imageFor={() => caseImage(item)} /></div><aside className="cr-detail-info"><span className="cr-overline">{zh ? item.label : item.labelEn}</span><h1>{zh ? item.title : item.en}</h1><p>{zh ? item.brief : item.briefEn}</p><div className="cr-detail-tags"><span>{zh ? "可编辑文案" : "Editable copy"}</span><span>{zh ? "独立生成每屏" : "Independent sections"}</span><span>{zh ? "保留商品原图" : "Product locked"}</span></div><Link className="cr-primary-button" href={`/commerce?case=${item.id}`}><Sparkles size={17} />{zh ? "使用这份版式" : "Use this layout"}<ArrowUpRight size={17} /></Link><div className="cr-detail-section"><h2>{zh ? "从参考，到你的作品" : "From reference to your creation"}</h2><div className="cr-reference-row"><Image src={caseImage(item)} width={90} height={108} alt={zh ? "摄影参考原图" : "Original photography reference"} /><div><strong>{zh ? "原始摄影参考" : "Original photo reference"}</strong><p>{zh ? "右侧说明与页面排版由本站设计。预览反复使用同一张摄影原图演示版式，并非 AI 多视角生成。" : "This study uses one original photograph across layouts. It does not demonstrate AI generated viewpoints."}</p></div></div></div><div className="cr-detail-section"><h2>{zh ? "这份案例的创作结构" : "The structure behind the story"}</h2><ol className="cr-case-steps">{sections.map(s => <li key={s.id}><span>{s.eyebrow.split(" /")[0]}</span><div>{s.title}<small>{s.layout === "cover" ? zh ? "大幅主视觉 · 标题留白" : "Full-bleed visual · Open typography" : s.layout === "split" ? zh ? "图文分栏 · 信息清晰" : "Split composition · Clear hierarchy" : zh ? "细节聚焦 · 杂志留白" : "Inset visual · Editorial space"}</small></div></li>)}</ol></div><div className="cr-detail-section"><div className="cr-copy-heading"><h2>{zh ? "创作描述" : "Creative prompt"}</h2><button onClick={async () => { try { await navigator.clipboard.writeText(zh ? item.brief : item.briefEn); setCopied(true); } catch { setNotice(zh ? "复制失败，请选中下方文本复制。" : "Select the prompt below to copy it."); } }}>{copied ? <Check size={14} /> : <Copy size={14} />}{zh ? "复制" : "Copy"}</button></div><p className="cr-prompt-text">{zh ? item.brief : item.briefEn}</p>{notice && <p role="status">{notice}</p>}</div><small className="cr-detail-disclaimer">{zh ? "参考素材来源：Unsplash。画面中的商标属于其所有者，案例不代表品牌合作或生成效果承诺。" : "Photography: Unsplash. Trademarks belong to their owners. This study does not imply affiliation or promise model output quality."}</small></aside></div></div></CreativeShell>;
}
