"use client";
import { useTheme } from "next-themes";
import { useLocale } from "next-intl";
import { useSession } from "next-auth/react";
import { Link, usePathname } from "@/i18n/navigation";
import { Aperture, Compass, House, Images, LayoutGrid, ShoppingBag, ArrowUpRight, CircleHelp, Zap, Globe2, SunMoon } from "lucide-react";
import "./discover.css";
import "./creative-direction.css";
export default function CreativeShell({ children }) {
  const { resolvedTheme, setTheme } = useTheme();
  const zh = useLocale() === "zh", path = usePathname(), { data: session } = useSession();
  const links = [["/", House, "创作首页", "Create"], ["/explore", Compass, "灵感发现", "Explore"], ["/commerce", ShoppingBag, "电商套图 Agent", "Commerce Agent"], ["/studio-v2", LayoutGrid, "自由画布", "Canvas"], ["/projects", Images, "我的作品", "My works"]];
  return <div className="cr-shell"><aside className="cr-sidebar"><Link href="/" className="cr-logo" aria-label="ModelShot"><Aperture size={29} strokeWidth={1.4} /><span>ModelShot<small>MAKE ROOM FOR IMAGINATION</small></span></Link><div className="cr-workspace-label">{zh ? "创意工作空间" : "YOUR CREATIVE SPACE"}</div><nav aria-label={zh ? "创作导航" : "Creative navigation"}>{links.map(([href, Icon, cn, en]) => <Link key={href} href={href} aria-label={zh ? cn : en} title={zh ? cn : en} className={path === href || href === "/explore" && path.startsWith("/explore/") ? "active" : ""}><Icon size={18} /><span>{zh ? cn : en}</span>{href === "/commerce" && <small>NEW</small>}</Link>)}</nav><div className="cr-sidebar-bottom"><div className="cr-upgrade"><span className="cr-overline">CREATE SOMETHING GREAT</span><p>{zh ? "让好想法，多一点可能。" : "Make more room for good ideas."}</p><Link href="/pricing">{zh ? "查看创作方案" : "Explore plans"}<ArrowUpRight size={15} /></Link></div><Link className="cr-support" href="/explore"><CircleHelp size={16} />{zh ? "从一个案例开始" : "Start with a reference"}</Link><Link className="cr-account" href={session?.user ? "/account" : "/login?callbackUrl=/commerce"}><span className="cr-avatar">{session?.user ? (session.user.name || session.user.email).slice(0, 1).toUpperCase() : "M"}</span><span>{session?.user ? session.user.name || (zh ? "我的账户" : "My account") : zh ? "登录，保存你的创意" : "Sign in to save your ideas"}<small>{zh ? "你的下一件作品，从这里开始" : "Your next creation starts here"}</small></span></Link></div></aside><div className="cr-main"><header className="cr-topbar"><span><span className="cr-live-dot" /><strong className="cr-wordmark">ModelShot<span> / {zh ? "创意工作室" : "Creative studio"}</span></strong></span><div><button className="cr-theme-toggle" aria-label={zh ? "切换明暗主题" : "Toggle color theme"} title={zh ? "切换明暗主题" : "Toggle color theme"} onClick={() => setTheme(resolvedTheme === "dark" ? "light" : "dark")}><SunMoon size={17} /></button><Link href={path} locale={zh ? "en" : "zh"} aria-label={zh ? "Switch to English" : "切换中文"}><Globe2 size={15} />{zh ? "EN" : "中文"}</Link><Link href="/account"><Zap size={14} />{session?.user?.credits ?? "—"}</Link><Link className="cr-top-cta" href={session?.user ? "/account" : `/login?callbackUrl=${encodeURIComponent(path)}`}>{session?.user ? zh ? "我的账户" : "Account" : zh ? "登录" : "Sign in"}<ArrowUpRight size={14} /></Link></div></header>{children}<footer className="cr-footer"><span>ModelShot © {new Date().getFullYear()} · {zh ? "让想象有形" : "Make imagination visible"}</span><span>{zh ? "案例为摄影素材与版式演绎，非模型实测效果。" : "References use photography and layout studies, not model output."}</span></footer></div></div>;
}
