"use client";
import Image from "next/image";
import { useEffect, useState } from "react";
import { useLocale } from "next-intl";
import { useSession } from "next-auth/react";
import { Link } from "@/i18n/navigation";
import { ArrowUpRight, LayoutGrid, ShoppingBag, Plus, FolderOpen } from "lucide-react";
import { api } from "@/lib/client-api";
import CreativeShell from "./CreativeShell";
export default function CreativeProjects() {
  const zh = useLocale() === "zh", { status } = useSession(), [rows, setRows] = useState(null), [filter, setFilter] = useState("all"), [error, setError] = useState("");
  useEffect(() => { if (status !== "authenticated") return; const controller = new AbortController(); api("/api/studio/documents", { signal: controller.signal }).then(setRows).catch(e => { if (!controller.signal.aborted) setError(e.message); }); return () => controller.abort(); }, [status]);
  const shown = (rows || []).filter(p => filter === "all" || p.kind === filter);
  return <CreativeShell><section className="cr-explore-heading"><span className="cr-overline">YOUR CREATIVE COLLECTION</span><h1>{zh ? "每一个想法，都值得留下。" : "Every idea deserves a place."}</h1><p>{zh ? "电商分镜与自由画布，随时回来继续创作。" : "Your storyboards and canvases, ready when inspiration returns."}</p></section><section className="cr-inspiration"><div className="cr-filter-bar"><div className="cr-categories">{[["all", "全部项目", "All projects"], ["commerce", "电商套图", "Commerce"], ["canvas", "自由画布", "Canvas"]].map(([id, cn, en]) => <button key={id} className={filter === id ? "active" : ""} onClick={() => setFilter(id)}>{zh ? cn : en}</button>)}</div><Link className="cr-project-new" href="/commerce"><Plus size={15} />{zh ? "开始新作品" : "New creation"}</Link></div>{error && <p role="alert">{error}</p>}{status === "unauthenticated" ? <div className="cr-empty-projects"><FolderOpen size={38} strokeWidth={1} /><h2>{zh ? "为你的创意，留一个位置" : "A home for your ideas"}</h2><p>{zh ? "登录后查看已保存的电商项目与画布。" : "Sign in to see saved storyboards and canvases."}</p><Link className="cr-primary-button" href="/login?callbackUrl=/projects">{zh ? "登录我的工作空间" : "Sign in to your workspace"}</Link></div> : rows === null ? <p className="cr-source-note">{zh ? "正在打开作品集…" : "Opening your collection…"}</p> : shown.length ? <div className="cr-project-grid">{shown.map(row => <Link href={`/${row.kind === "commerce" ? "commerce" : "studio-v2"}?document=${row.id}`} key={row.id} className="cr-project-card"><div>{row.coverAssetId ? <Image unoptimized src={`/api/assets/${row.coverAssetId}`} alt={row.name} fill sizes="400px" /> : <LayoutGrid size={40} strokeWidth={1} />}<span>{row.kind === "commerce" ? <ShoppingBag size={13} /> : <LayoutGrid size={13} />}{row.kind === "commerce" ? zh ? "电商套图" : "Commerce" : zh ? "自由画布" : "Canvas"}</span></div><h2>{row.name}<ArrowUpRight size={15} /></h2><p>{new Date(row.updatedAt).toLocaleDateString(zh ? "zh-CN" : "en-US")} · {row.count} {row.kind === "commerce" ? zh ? "屏" : "sections" : zh ? "图层" : "layers"}</p></Link>)}</div> : <div className="cr-empty-projects"><FolderOpen size={38} strokeWidth={1} /><h2>{zh ? "第一件作品，即将发生。" : "Your first creation is waiting."}</h2><Link href="/explore" className="cr-primary-button">{zh ? "去寻找一点灵感" : "Find some inspiration"}<ArrowUpRight size={15} /></Link></div>}<Link className="cr-legacy-link" href="/gallery">{zh ? "查看旧版电商历史记录" : "View earlier commerce production history"}<ArrowUpRight size={12} /></Link></section></CreativeShell>;
}
