"use client";
import { useState } from "react";
import { useLocale } from "next-intl";
import { Link, useRouter } from "@/i18n/navigation";
import { ArrowUp, ArrowUpRight, Search, Sparkles, MessageCircle, Zap, ShoppingBag, SlidersHorizontal, ImagePlus, ChevronDown, WandSparkles } from "lucide-react";
import { CASES, CATEGORIES } from "@/lib/commerce/catalog";
import CreativeShell from "./CreativeShell";
import CommerceLauncher from "./CommerceLauncher";
import CaseArtwork from "./CaseArtwork";
import StudioShowcase from "./StudioShowcase";

export function CaseCard({ item, zh }) {
  return <Link href={`/explore/${item.id}`} className={`cr-case cr-case-${item.theme} cr-case-${item.span}`} aria-label={zh ? item.title : item.en}><div className="cr-case-art"><CaseArtwork item={item} zh={zh} /><span className="cr-case-open"><ArrowUpRight size={18} /></span></div><div className="cr-case-caption"><div><h3>{zh ? item.title : item.en}</h3><p>{zh ? item.label : item.labelEn}</p></div><ArrowUpRight size={15} /></div></Link>;
}

export default function DiscoverHome({ explore = false }) {
  const zh = useLocale() === "zh", router = useRouter();
  const [mode, setMode] = useState("chat"), [prompt, setPrompt] = useState(""), [category, setCategory] = useState("all"), [query, setQuery] = useState("");
  const visible = CASES.filter(c => (category === "all" || c.category === category) && `${c.title} ${c.en} ${c.label} ${c.labelEn} ${c.product}`.toLowerCase().includes(query.toLowerCase()));
  function start() { if (mode === "commerce") router.push(`/commerce?brief=${encodeURIComponent(prompt)}`); else router.push(`/studio-v2?mode=${mode}&prompt=${encodeURIComponent(prompt)}`); }
  return <CreativeShell>{!explore ? <section className="cr-hero"><div className="cr-hero-content"><div className="cr-hero-kicker"><span />YOUR NEXT GREAT IMAGE STARTS HERE</div><h1>{zh ? <>让想象，<em>有形。</em></> : <>Give imagination <em>form.</em></>}</h1><p className="cr-hero-subtitle">{zh ? "一张图片的可能，不止一张图片。和 AI 一起，创作下一个好作品。" : "An image is only the beginning. Create your next great work with AI."}</p><div className="cr-home-composer"><div className="cr-mode-tabs" role="tablist" aria-label={zh ? "创作模式" : "Creative mode"}>{[["chat", MessageCircle, "对话", "Chat"], ["quick", Zap, "快速", "Quick"], ["commerce", ShoppingBag, "电商套图 Agent", "Commerce Agent"]].map(([id, Icon, cn, en]) => <button key={id} role="tab" aria-selected={mode === id} onClick={() => setMode(id)}><Icon size={15} />{zh ? cn : en}{id === "commerce" && <span>NEW</span>}</button>)}</div>{mode === "commerce" ? <CommerceLauncher initialDescription={prompt} /> : <><textarea aria-label={zh ? "描述你的创意" : "Describe your idea"} value={prompt} maxLength={2400} onChange={e => setPrompt(e.target.value)} placeholder={mode === "commerce" ? zh ? "描述产品、卖点和想要的风格，下一步上传产品图与参考图…" : "Describe your product and art direction. Add product and style references next…" : zh ? "说说你的想法吧：一张有呼吸感的产品海报，一组电影感的画面…" : "An airy product poster, a cinematic scene… What will you create?"} /><div className="cr-composer-bottom"><button onClick={start} className="cr-upload-shortcut"><ImagePlus size={17} /><span>{zh ? "添加图片" : "Add image"}</span></button><span className="cr-model-label"><Sparkles size={13} />{mode === "commerce" ? "Commerce Studio" : "Image Studio"}<ChevronDown size={12} /></span><button className="cr-send" aria-label={zh ? "开始创作" : "Start creating"} onClick={start}><ArrowUp size={22} /></button></div></>}</div><div className="cr-quick-links">{[["quiet-living", "电商详情页", "Product stories"], ["botanical-light", "产品摄影", "Product photography"], ["red-motion", "创意海报", "Creative posters"]].map(([id, cn, en]) => <Link href={`/explore/${id}`} key={id}><WandSparkles size={13} />{zh ? cn : en}<ArrowUpRight size={12} /></Link>)}</div></div><StudioShowcase zh={zh} /></section> : <section className="cr-explore-heading"><span className="cr-overline">THE INSPIRATION LIBRARY</span><h1>{zh ? "好作品，从灵感开始。" : "Good work starts with inspiration."}</h1><p>{zh ? "拆解一份创意，带走一种风格。把喜欢的案例，变成自己的作品。" : "Explore a composition. Borrow an approach. Make something of your own."}</p></section>}
    <section className="cr-inspiration"><div className="cr-section-heading"><div><h2><Sparkles size={19} />{zh ? "灵感发现" : "Discover inspiration"}<span>{zh ? "总有一种，打动你" : "Find your next direction"}</span></h2></div>{!explore && <Link href="/explore">{zh ? "探索全部" : "Explore all"}<ArrowUpRight size={15} /></Link>}</div><div className="cr-filter-bar"><div className="cr-categories" role="group" aria-label={zh ? "案例分类" : "Case categories"}>{CATEGORIES.map(([id, cn, en]) => <button key={id} className={category === id ? "active" : ""} onClick={() => setCategory(id)}>{zh ? cn : en}</button>)}</div><label className="cr-search"><Search size={15} /><input value={query} onChange={e => setQuery(e.target.value)} aria-label={zh ? "搜索灵感" : "Search inspiration"} placeholder={zh ? "搜索灵感" : "Search inspiration"} /><SlidersHorizontal size={13} /></label></div><div className="cr-masonry">{visible.map(item => <CaseCard key={item.id} item={item} zh={zh} />)}</div>{!visible.length && <div className="cr-no-results">{zh ? "暂时没有匹配的案例，试试其他关键词。" : "No matching references. Try a different search."}<button onClick={() => { setQuery(""); setCategory("all"); }}>{zh ? "查看全部" : "Show all"}</button></div>}<p className="cr-source-note">{zh ? "摄影参考 × 版式研究 · 图片来自 Unsplash，案例不代表本产品的 AI 生成效果。" : "Photography × layout studies · Unsplash references, not AI output from this product."}</p></section></CreativeShell>;
}
